---

- name: WAZUH SERVER | Manage Debian environment
  import_tasks: debian.yml
  when: ansible_os_family == 'Debian' or ansible_os_family == 'Ubuntu'

- name: WAZUH SERVER | Manage Redhat environment
  import_tasks: redhat.yml
  when: ansible_os_family == 'RedHat' or ansible_os_family == 'CentOS'

- name: WAZUH SERVER | Installation
  package:
    name: "wazuh-manager={{ wazuh_server_version }}*"
    update_cache: yes
    state: present
  notify: Restart wazuh-server
  tags: update-wazuh_server

- name: WAZUH SERVER | Configuration
  template:
    src: var/ossec/etc/ossec.conf.j2
    dest: /var/ossec/etc/ossec.conf
    owner: root
    group: root
    mode: 0644

- name: WAZUH SERVER | Rules configuration
  template:
    src: var/ossec/etc/rules/{{ item }}.j2
    dest: /var/ossec/etc/rules/{{ item }}
    owner: root
    group: root
    mode: 0644
  with_items:
    - local_rules.xml
