---

- name: WAZUH API ON REDHAT | Add repository
  yum_repository:
    name: wazuh
    description: Elastic repository for 6.x packages
    baseurl: "{{ wazuh_api_yum_repository }}"
    gpgcheck: yes
    gpgkey: "{{ wazuh_api_yum_key }}"
